services:
  trello-nextapp:
    build:
      context: .
    container_name: trello-nextapp
    environment:
      CLERK_SECRET_KEY: ${{secrets.CLERK_SECRET_KEY}}
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY}}
      NEXT_PUBLIC_SUPABASE_URL: ${{secrets.NEXT_PUBLIC_SUPABASE_URL}}
    ports:
      - "3000:3000"
