services:
  trello-nextapp:
    image: ayeshaazad/trello-nextapp
    environment:
      CLERK_SECRET_KEY: ${clerk-secret-key}
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${next-public-clerk-publishable-key}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${next-public-supabase-anon-key}
      NEXT_PUBLIC_SUPABASE_URL: ${next-public-supabase-url}
    ports:
      - "3050:3000"
