name: Deployment for Trello Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Node JS Setup
        uses: actions/setup-node@v5
        with:
          node-version: "20"
          cache: "npm"

      - name: Installing Dependencies
        run: npm ci

      - name: Docker build
        run: docker compose build
        env:
          CLERK_SECRET_KEY: ${{secrets.CLERK_SECRET_KEY}}
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY}}
          NEXT_PUBLIC_SUPABASE_URL: ${{secrets.NEXT_PUBLIC_SUPABASE_URL}}

      - name: Docker login
        run: echo ${{secrets.DOCKER_PAT}} | docker login --username ayeshaazad --password-stdin

      - name: Docker Push
        run: docker compose push

      - name: Running Build
        run: npm run build
